module.exports = {
  STATE_SAVE: 'STATE_SAVE',
  STATE_SAVE_IMMEDIATE: 'STATE_SAVE_IMMEDIATE',

  UPDATE: 'UPDATE',

  CONFIRMATION: {
    SHOW: 'CONFIRMATION:SHOW',
    HIDE: 'CONFIRMATION:HIDE',
    CONFIRM: 'CONFIRMATION:CONFIRM',
    CANCEL: 'CONFIRMATION:CANCEL',
  },
  NAVS: {
    GO_TO_PAGE: 'GO_TO_PAGE',
  },
  TODO_LIST: {
    ADD_TODO: 'ADD_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    DELETE_TODO: 'DELETE_TODO',
  },
  TAGS: {
    ADD_TAG: 'ADD_TAG',
    UPDATE_TAG: 'UPDATE_TAG',
    DELETE_TAG: 'DELETE_TAG',
  },
  REWARDS: {
    ADD_REWARD: 'ADD_REWARD',
    UPDATE_REWARD: 'UPDATE_REWARD',
    TOGGLE_REWARD: 'TOGGLE_REWARD',
    DELETE_REWARD: 'DELETE_REWARD',
  }
}
